### ISSUE TITLE
gitignore is ignored

### ISSUE THREAD

**Issue by jlmayfield** [monmouth-college-cs/ColorMeBlind#6]
It looks like the gitignore file in the project is an rtf file and not raw text. This is causing git to ignore it (ironic) and putting a lot of files in the repo that don't need to be there.

**Comment by phein** [comment]
I did not have have notepad or anything like that so I used TextEdit to create a text file. Thank you!

**Comment by jlmayfield** [comment]
@phein I'll wager that TextEdit lets you save as raw text (txt) file. You saved it as rich text format (rft) which include font information and other things. It's not raw text.  Just be sure to use txt format for things like the .gitignore file and if needed, remove the .txt extension. Not a huge deal.
